version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=nestjs
      - DATABASE_PASSWORD=nestjs
      - DATABASE_NAME=nestjs
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=nestjs
      - POSTGRES_PASSWORD=nestjs
      - POSTGRES_DB=nestjs
    ports:
      - "5432:5432"
